fixtures:
  forge_modules:
    concat:
      repo: 'puppetlabs-concat'
      ref: '2.2.1'
    stdlib: 'puppetlabs-stdlib'
    augeas_core: 'puppetlabs-augeas_core'
  symlinks:
    collectd: "#{source_dir}"
