---
language: ruby
sudo: false
addons:
  apt:
    packages:
      - libaugeas-dev
    sources:
      - augeas
cache: bundler
bundler_args: --without system_tests
script: ["bundle exec rake validate", "bundle exec rake lint", "bundle exec rake spec SPEC_OPTS='--format documentation'"]
matrix:
  fast_finish: true
  include:
  - rvm: 2.1
    env: PUPPET_GEM_VERSION="~> 4.0"
  - rvm: 2.4
    env: PUPPET_GEM_VERSION="~> 5.0"
  - rvm: 2.5
    env: PUPPET_GEM_VERSION="~> 6.0"
  - rvm: default
    sudo: required
    services: docker
    env:
      - PUPPET_INSTALL_TYPE=agent
      - BEAKER_IS_PE=no
      - BEAKER_PUPPET_COLLECTION=puppet5
      - BEAKER_debug=true
      - BEAKER_setfile=debian6-64{hypervisor=docker}
    bundler_args:
    script: bundle exec rspec spec/acceptance/*_spec.rb
  - rvm: default
    sudo: required
    services: docker
    env:
      - PUPPET_INSTALL_TYPE=agent
      - BEAKER_IS_PE=no
      - BEAKER_PUPPET_COLLECTION=puppet5
      - BEAKER_debug=true
      - BEAKER_setfile=debian7-64{hypervisor=docker}
    bundler_args:
    script: bundle exec rspec spec/acceptance/*_spec.rb
  - rvm: default
    sudo: required
    services: docker
    env:
      - PUPPET_INSTALL_TYPE=agent
      - BEAKER_IS_PE=no
      - BEAKER_PUPPET_COLLECTION=puppet5
      - BEAKER_debug=true
      - BEAKER_setfile=debian8-64{hypervisor=docker}
    bundler_args:
    script: bundle exec rspec spec/acceptance/*_spec.rb
  - rvm: default
    sudo: required
    services: docker
    env:
      - PUPPET_INSTALL_TYPE=agent
      - BEAKER_IS_PE=no
      - BEAKER_PUPPET_COLLECTION=puppet5
      - BEAKER_debug=true
      - BEAKER_setfile=debian9-64{hypervisor=docker}
    bundler_args:
    script: bundle exec rspec spec/acceptance/*_spec.rb
  - rvm: default
    sudo: required
    services: docker
    env:
      - PUPPET_INSTALL_TYPE=agent
      - BEAKER_IS_PE=no
      - BEAKER_PUPPET_COLLECTION=puppet5
      - BEAKER_debug=true
      - BEAKER_setfile=centos5-64{hypervisor=docker}
    bundler_args:
    script: bundle exec rspec spec/acceptance/*_spec.rb
  - rvm: default
    sudo: required
    services: docker
    env:
      - PUPPET_INSTALL_TYPE=agent
      - BEAKER_IS_PE=no
      - BEAKER_PUPPET_COLLECTION=puppet5
      - BEAKER_debug=true
      - BEAKER_setfile=centos6-64{hypervisor=docker}
    bundler_args:
    script: bundle exec rspec spec/acceptance/*_spec.rb
  - rvm: default
    sudo: required
    services: docker
    env:
      - PUPPET_INSTALL_TYPE=agent
      - BEAKER_IS_PE=no
      - BEAKER_PUPPET_COLLECTION=puppet5
      - BEAKER_debug=true
      - BEAKER_setfile=centos7-64{hypervisor=docker}
    bundler_args:
    script: bundle exec rspec spec/acceptance/*_spec.rb
  - rvm: default
    sudo: required
    services: docker
    env:
      - PUPPET_INSTALL_TYPE=agent
      - BEAKER_IS_PE=no
      - BEAKER_PUPPET_COLLECTION=puppet5
      - BEAKER_debug=true
      - BEAKER_setfile=ubuntu1204-64{hypervisor=docker}
    bundler_args:
    script: bundle exec rspec spec/acceptance/*_spec.rb
  - rvm: default
    sudo: required
    services: docker
    env:
      - PUPPET_INSTALL_TYPE=agent
      - BEAKER_IS_PE=no
      - BEAKER_PUPPET_COLLECTION=puppet5
      - BEAKER_debug=true
      - BEAKER_setfile=ubuntu1404-64{hypervisor=docker}
    bundler_args:
    script: bundle exec rspec spec/acceptance/*_spec.rb
  - rvm: default
    sudo: required
    services: docker
    env:
      - PUPPET_INSTALL_TYPE=agent
      - BEAKER_IS_PE=no
      - BEAKER_PUPPET_COLLECTION=puppet5
      - BEAKER_debug=true
      - BEAKER_setfile=ubuntu1604-64{hypervisor=docker}
    bundler_args:
    script: bundle exec rspec spec/acceptance/*_spec.rb
  - rvm: default
    sudo: required
    services: docker
    env:
      - PUPPET_INSTALL_TYPE=agent
      - BEAKER_IS_PE=no
      - BEAKER_PUPPET_COLLECTION=puppet5
      - BEAKER_debug=true
      - BEAKER_setfile=ubuntu1804-64{hypervisor=docker}
    bundler_args:
    script: bundle exec rspec spec/acceptance/*_spec.rb
notifications:
  email: false
deploy:
  provider: puppetforge
  user: camptocamp
  password:
    secure: "ay5H/Tj63r6bfomb7F2AZ8mQdVcr4YNMak9kt5ZAenOFMXvruFtDJsnQLL3v910bhXlNkbnA1gZ4zkzx9dvBk6Em8zwLfWiyNumy61u2UgzEYRYu5tEVWJ5o5YrpvCBcObtl/OIyy8xdq4r7d/zBN8Slax3gTjPywSWkP7TYrIs="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish if our main Ruby target builds
    rvm: 2.4
